name: Docs Deployment
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          yarn
          yarn build
          mv ./storybook-static ./docs/storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
          SINGLE_COMMIT: true
          GIT_CONFIG_NAME: lukasbachbot
          GIT_CONFIG_EMAIL: bot@noreply.lukasbach.com
